USE master;
GO
IF DB_ID('CityTours') IS NOT NULL 
BEGIN
	DROP DATABASE CityTours
END
CREATE DATABASE CityTours;
GO
USE CityTours;
GO

IF OBJECT_ID('Users') IS NOT NULL DROP TABLE users;
GO

BEGIN TRANSACTION
CREATE TABLE Users(
	user_id		INT	IDENTITY(1,1),
	email		VARCHAR(254)	NOT NULL,
	password	VARCHAR(64)		NOT NULL,
	salt		VARCHAR(64)		NOT NULL,
	role		VARCHAR(16)		DEFAULT('user'),
	CONSTRAINT Users_PK PRIMARY KEY (user_id)
)
COMMIT TRANSACTION
GO